<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="FluentAssertions" Version="7.2.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.13.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Consolidation.Api\Consolidation.Api.csproj" />
    <ProjectReference Include="..\..\src\Consolidation.Infrastructure\Consolidation.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Consolidation.Worker\Consolidation.Worker.csproj" />
  </ItemGroup>

</Project>