/**
 * The contract of `docs/api-contracts.md`, declared as types.
 *
 * This is a second, hand-written declaration of the contract — the OpenAPI
 * document generated by each API is the first. Nothing today keeps them in sync
 * automatically; generating these from `/openapi/v1.json` is registered as a
 * future improvement in ADR-015.
 */

export type TransactionType = 'CREDIT' | 'DEBIT';

/** §2.1 — the DTO returned by POST, GET by id and each item of the list. */
export interface Transaction {
  id: string;
  type: TransactionType;
  amount: number;
  occurredAt: string;
  description: string | null;
  createdAt: string;
}

/** §2.3 — cursor page. There is no `totalCount`, by design (ADR-014). */
export interface TransactionPage {
  items: Transaction[];
  nextCursor: string | null;
  hasMore: boolean;
}

/** §3.1 — `updatedAt` is null for a day that never received an event. */
export interface DailyBalance {
  date: string;
  totalCredits: number;
  totalDebits: number;
  balance: number;
  updatedAt: string | null;
}

/** §4 — Problem Details (RFC 7807) with our two extensions. */
export interface ProblemDetails {
  type: string;
  title: string;
  status: number;
  detail: string;
  instance?: string;
  correlationId?: string;
  errors?: Record<string, string[]>;
}

export interface ListTransactionsQuery {
  limit?: number;
  cursor?: string;
  startDate?: string;
  endDate?: string;
}

/**
 * `occurredOn` is a civil date from a date picker, not an instant. The client
 * turns it into an instant with an explicit offset before sending — the
 * contract rejects an instant without one rather than guessing a timezone.
 */
export interface CreateTransactionInput {
  type: TransactionType;
  amount: number;
  occurredOn?: string;
  description?: string;
}
